# Generated by Django 3.2.5 on 2021-07-21 08:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Closed', 'Closed')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('company', models.CharField(max_length=50)),
                ('address', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('smtp_server', models.CharField(blank=True, max_length=50)),
                ('smtp_email', models.CharField(blank=True, max_length=50)),
                ('smtp_password', models.CharField(blank=True, max_length=10)),
                ('smtp_port', models.CharField(blank=True, max_length=5)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('logo', models.ImageField(blank=True, upload_to='images/')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=50)),
                ('telegram', models.CharField(blank=True, max_length=50)),
                ('shopping_features_img_1', models.FileField(blank=True, upload_to='images/')),
                ('shopping_features_title_1', models.CharField(max_length=150)),
                ('shopping_features_description_1', models.CharField(max_length=150)),
                ('shopping_features_img_2', models.FileField(blank=True, upload_to='images/')),
                ('shopping_features_title_2', models.CharField(max_length=150)),
                ('shopping_features_description_2', models.CharField(max_length=150)),
                ('shopping_features_img_3', models.FileField(blank=True, upload_to='images/')),
                ('shopping_features_title_3', models.CharField(max_length=150)),
                ('shopping_features_description_3', models.CharField(max_length=150)),
                ('shopping_features_img_4', models.FileField(blank=True, upload_to='images/')),
                ('shopping_features_title_4', models.CharField(max_length=150)),
                ('shopping_features_description_4', models.CharField(max_length=150)),
                ('shopping_features_img_5', models.FileField(blank=True, upload_to='images/')),
                ('shopping_features_title_5', models.CharField(max_length=150)),
                ('shopping_features_description_5', models.CharField(max_length=150)),
                ('aboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('contact', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('references', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='brandImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.setting')),
            ],
        ),
    ]
