# Generated by Django 3.2.5 on 2021-07-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='about_us',
            new_name='aboutus',
        ),
    ]
