# Generated by Django 3.2.5 on 2021-07-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210720_0644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_description',
            new_name='shopping_features_description1',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_title',
            new_name='shopping_features_description2',
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_description3',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_description4',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_description5',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_title1',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_title2',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_title3',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_title4',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_title5',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
