# Generated by Django 3.2.5 on 2021-07-20 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210720_0647'),
    ]

    operations = [
        migrations.CreateModel(
            name='brandImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_description1',
            new_name='shopping_features_description_1',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_description2',
            new_name='shopping_features_description_2',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_description3',
            new_name='shopping_features_description_3',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_description4',
            new_name='shopping_features_description_4',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_description5',
            new_name='shopping_features_description_5',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='brand_img',
            new_name='shopping_features_img_1',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_img',
            new_name='shopping_features_img_2',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_title1',
            new_name='shopping_features_title_1',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_title2',
            new_name='shopping_features_title_2',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_title3',
            new_name='shopping_features_title_3',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_title4',
            new_name='shopping_features_title_4',
        ),
        migrations.RenameField(
            model_name='setting',
            old_name='shopping_features_title5',
            new_name='shopping_features_title_5',
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_img_3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_img_4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='shopping_features_img_5',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
