# Generated by Django 3.2.5 on 2021-07-20 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210720_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandimages',
            name='setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.setting'),
            preserve_default=False,
        ),
    ]
