# Generated by Django 3.2.5 on 2021-07-20 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_brandimages_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='shopping_features_img_1',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
