# Generated by Django 3.2.5 on 2021-07-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_setting_shopping_features_img_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='shopping_features_img_2',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='shopping_features_img_3',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='shopping_features_img_4',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='shopping_features_img_5',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
