# Generated by Django 3.2.5 on 2021-07-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210720_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس با ما'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=11, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='ip',
            field=models.CharField(blank=True, max_length=20, verbose_name='ای پی'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, max_length=255, verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('جدید', 'جدید'), ('خوانده شده', 'خوانده شده'), ('بستن', 'بستن')], default='جدید', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=255, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='به روز شده در'),
        ),
    ]
